import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  map: {
    flex: 1,
  },
  topBar: {
    position: 'absolute',
    top: 18,
    left: 16,
    right: 16,
    gap: 12,
  },
  badge: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
  },
  badgeTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  badgeText: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
  },
  toggleButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  toggleButtonText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryMapButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryMapButtonText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryMapButtonActive: {
    backgroundColor: '#0f172a',
  },
  secondaryMapButtonTextActive: {
    color: '#f8fafc',
  },
  followButton: {
    alignSelf: 'flex-start',
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followButtonDisabled: {
    opacity: 0.75,
  },
  followIconOuterRing: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followIconInnerRing: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followIconDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#94a3b8',
  },
  followIconDotActive: {
    backgroundColor: '#22c55e',
  },
  detailsCard: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 112,
    flexDirection: 'row',
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    overflow: 'hidden',
    minHeight: 140,
  },
  thumbnail: {
    width: 120,
    backgroundColor: '#cbd5e1',
  },
  detailsText: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
  },
  detailsTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  detailsStatus: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  detailsBody: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 20,
  },
  poleMarkerWrap: {
    alignItems: 'center',
  },
  poleImageBillboard: {
    width: 58,
    height: 42,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    backgroundColor: '#e2e8f0',
  },
  poleImageBillboardSelected: {
    width: 74,
    height: 54,
    borderWidth: 3,
    borderColor: '#f59e0b',
  },
  poleImage: {
    width: '100%',
    height: '100%',
  },
  poleMarkerTail: {
    width: 0,
    height: 0,
    marginTop: -1,
    borderLeftWidth: 9,
    borderRightWidth: 9,
    borderTopWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'rgba(255, 255, 255, 0.92)',
  },
  poleMarkerTailSelected: {
    borderLeftWidth: 11,
    borderRightWidth: 11,
    borderTopWidth: 14,
    borderTopColor: '#f59e0b',
  },
  bottomBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 20,
    padding: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  bottomBarButton: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBarButtonDisabled: {
    opacity: 0.72,
  },
  cameraIconBody: {
    width: 26,
    height: 18,
    borderRadius: 6,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  cameraIconTop: {
    position: 'absolute',
    top: -4,
    left: 4,
    width: 10,
    height: 6,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    backgroundColor: '#0f172a',
  },
  cameraIconLensOuter: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraIconLensInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#0f172a',
  },
  cameraModeDebug: {
    position: 'absolute',
    right: 16,
    bottom: 20,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
  },
  cameraModeDebugText: {
    color: '#f8fafc',
    fontSize: 11,
    fontWeight: '700',
  },
});
