import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  map: {
    flex: 1,
  },
  topBar: {
    position: 'absolute',
    top: 18,
    left: 16,
    right: 16,
    gap: 12,
    alignItems: 'flex-start',
  },
  badge: {
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: 'rgba(15, 23, 42, 0.88)',
  },
  badgeTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  badgeText: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
  },
  toggleButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#f8fafc',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  toggleButtonText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryMapButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  secondaryMapButtonText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  secondaryMapButtonActive: {
    backgroundColor: '#0f172a',
  },
  secondaryMapButtonTextActive: {
    color: '#f8fafc',
  },
  friendsDropdownWrap: {
    zIndex: 30,
    alignItems: 'flex-start',
    gap: 10,
  },
  friendsDrawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    zIndex: 20,
  },
  friendsDrawer: {
    position: 'absolute',
    top: 74,
    left: 16,
    right: 16,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 8,
    zIndex: 25,
  },
  friendsDrawerHeader: {
    marginBottom: 14,
    gap: 12,
  },
  friendsDrawerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  friendsDrawerTitle: {
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '800',
  },
  addFriendButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addFriendButtonText: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 24,
  },
  addFriendSearchInput: {
    borderRadius: 16,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '600',
  },
  friendsDrawerList: {
    gap: 2,
  },
  friendDrawerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 10,
  },
  friendStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 6,
    backgroundColor: '#cbd5e1',
  },
  friendStatusDotOnline: {
    backgroundColor: '#22c55e',
  },
  friendMeta: {
    flex: 1,
    gap: 2,
  },
  friendTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  friendUsername: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '700',
    flexShrink: 0,
  },
  friendCatchText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
    textAlign: 'right',
  },
  friendLastOnline: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  nearbyBirdCardWrap: {
    position: 'absolute',
    right: 16,
  },
  nearbyBirdCard: {
    minWidth: 92,
    paddingTop: 8,
    paddingHorizontal: 8,
    paddingBottom: 10,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    alignItems: 'center',
    shadowColor: '#0f172a',
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 6,
  },
  nearbyBirdCardActive: {
    borderWidth: 2,
    borderColor: '#f59e0b',
  },
  nearbyBirdLabel: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  nearbyBirdImageFrame: {
    width: 66,
    height: 66,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#dbeafe',
  },
  nearbyBirdImage: {
    width: '100%',
    height: '100%',
  },
  nearbyBirdPlaceholder: {
    width: 66,
    height: 66,
    borderRadius: 18,
    backgroundColor: '#cbd5e1',
  },
  followButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followButtonFloating: {
    position: 'absolute',
    right: 16,
  },
  characterButton: {
    position: 'absolute',
    left: 8,
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.92)',
  },
  characterButtonImage: {
    width: 88,
    height: 88,
    borderRadius: 44,
  },
  characterOnlineDot: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#86efac',
    borderWidth: 2,
    borderColor: '#f8fafc',
  },
  followButtonDisabled: {
    opacity: 0.75,
  },
  followIconOuterRing: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followIconInnerRing: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  followIconDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#94a3b8',
  },
  followIconDotActive: {
    backgroundColor: '#22c55e',
  },
  detailsCard: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 112,
    flexDirection: 'row',
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    overflow: 'hidden',
    minHeight: 140,
  },
  thumbnail: {
    width: 120,
    backgroundColor: '#cbd5e1',
  },
  detailsText: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 6,
  },
  detailsTitle: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  detailsStatus: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  detailsBody: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 20,
  },
  detailsMeta: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    marginTop: 2,
  },
  poleMarkerWrap: {
    alignItems: 'center',
  },
  poleImageBillboard: {
    width: 58,
    height: 42,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.92)',
    backgroundColor: '#e2e8f0',
  },
  poleImageBillboardSelected: {
    width: 74,
    height: 54,
    borderWidth: 3,
    borderColor: '#f59e0b',
  },
  poleImage: {
    width: '100%',
    height: '100%',
  },
  poleMarkerTail: {
    width: 0,
    height: 0,
    marginTop: -1,
    borderLeftWidth: 9,
    borderRightWidth: 9,
    borderTopWidth: 12,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: 'rgba(255, 255, 255, 0.92)',
  },
  poleMarkerTailSelected: {
    borderLeftWidth: 11,
    borderRightWidth: 11,
    borderTopWidth: 14,
    borderTopColor: '#f59e0b',
  },
  bottomBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 20,
    padding: 0,
    backgroundColor: 'transparent',
    alignItems: 'center',
  },
  bottomBarButton: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomBarButtonDisabled: {
    opacity: 0.72,
  },
  cameraButtonCircle: {
    width: 60,
    height: 60,
    borderRadius: 36,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    elevation: 6,
  },
  cameraButtonImage: {
    width: 54,
    height: 54,
  },
  cameraModeDebug: {
    position: 'absolute',
    right: 16,
    bottom: 176,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.78)',
  },
  cameraModeDebugText: {
    color: '#f8fafc',
    fontSize: 11,
    fontWeight: '700',
  },
  authGateOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  authGateCard: {
    width: '100%',
    maxWidth: 320,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    paddingHorizontal: 22,
    paddingVertical: 22,
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 8,
    gap: 10,
  },
  authGateTitle: {
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '800',
  },
  authGateBody: {
    color: '#475569',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '600',
  },
  authGateButton: {
    alignSelf: 'flex-start',
    marginTop: 6,
    borderRadius: 999,
    backgroundColor: '#0f172a',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  authGateButtonText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  cameraOverlayBackdrop: {
    flex: 1,
    backgroundColor: '#020617',
  },
  cameraPreview: {
    ...StyleSheet.absoluteFillObject,
  },
  cameraPreviewFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0f172a',
  },
  cameraOverlayScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  cameraOverlayContent: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 64,
    paddingBottom: 56,
    paddingHorizontal: 24,
  },
  cameraOverlayHeader: {
    alignItems: 'center',
    gap: 6,
  },
  cameraOverlayTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
  },
  cameraOverlaySubtitle: {
    color: '#cbd5e1',
    fontSize: 14,
    fontWeight: '600',
  },
  cameraOverlayFrameWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraOverlayFrame: {
    width: '88%',
    aspectRatio: 3 / 4,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.28)',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
  },
  cameraOverlayCornerTopLeft: {
    position: 'absolute',
    top: 16,
    left: 16,
    width: 36,
    height: 36,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderColor: '#f8fafc',
    borderTopLeftRadius: 14,
  },
  cameraOverlayCornerTopRight: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 36,
    height: 36,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderColor: '#f8fafc',
    borderTopRightRadius: 14,
  },
  cameraOverlayCornerBottomLeft: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    width: 36,
    height: 36,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderColor: '#f8fafc',
    borderBottomLeftRadius: 14,
  },
  cameraOverlayCornerBottomRight: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    width: 36,
    height: 36,
    borderRightWidth: 4,
    borderBottomWidth: 4,
    borderColor: '#f8fafc',
    borderBottomRightRadius: 14,
  },
  cameraOverlayActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cameraOverlayMessageBox: {
    alignSelf: 'center',
    width: '88%',
    borderRadius: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    paddingHorizontal: 18,
    paddingVertical: 18,
    alignItems: 'center',
    gap: 10,
  },
  cameraOverlayMessageTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '800',
  },
  cameraOverlayMessageText: {
    color: '#cbd5e1',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  cameraOverlaySecondaryButton: {
    borderRadius: 999,
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  cameraOverlaySecondaryButtonText: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '700',
  },
  cameraOverlayCaptureButton: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 4,
    borderColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  cameraOverlayCaptureInner: {
    width: 62,
    height: 62,
    borderRadius: 31,
    backgroundColor: '#f8fafc',
  },
  characterScreen: {
    flex: 1,
    backgroundColor: '#f8fafc',
    paddingTop: 72,
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  characterScreenScroll: {
    paddingBottom: 24,
  },
  characterScreenHeader: {
    gap: 8,
    marginBottom: 32,
  },
  characterScreenTitle: {
    color: '#0f172a',
    fontSize: 32,
    fontWeight: '800',
  },
  characterScreenSubtitle: {
    color: '#475569',
    fontSize: 15,
    lineHeight: 22,
  },
  authModeRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  authModeButton: {
    borderRadius: 999,
    backgroundColor: '#e2e8f0',
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  authModeButtonActive: {
    backgroundColor: '#0f172a',
  },
  authModeButtonText: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '700',
  },
  authModeButtonTextActive: {
    color: '#f8fafc',
  },
  authCard: {
    borderRadius: 28,
    backgroundColor: '#e2e8f0',
    padding: 20,
    gap: 14,
  },
  authWelcomeCard: {
    borderRadius: 28,
    backgroundColor: '#e2e8f0',
    padding: 20,
    gap: 6,
  },
  authWelcomeEyebrow: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  authWelcomeUsername: {
    color: '#0f172a',
    fontSize: 28,
    fontWeight: '800',
  },
  authInput: {
    borderRadius: 16,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '600',
  },
  authStatusText: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '600',
  },
  authSubmitButton: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#0f172a',
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  authSubmitButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  gallerySection: {
    marginTop: 24,
    gap: 14,
  },
  gallerySectionHeader: {
    gap: 4,
  },
  gallerySectionTitle: {
    color: '#0f172a',
    fontSize: 24,
    fontWeight: '800',
  },
  gallerySectionSubtitle: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '600',
  },
  galleryStatusText: {
    color: '#64748b',
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -4,
  },
  galleryTile: {
    width: '33.3333%',
    paddingHorizontal: 4,
    paddingBottom: 8,
  },
  galleryImage: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 14,
    backgroundColor: '#cbd5e1',
  },
  characterScreenCloseButton: {
    alignSelf: 'flex-start',
    marginTop: 24,
    borderRadius: 999,
    backgroundColor: '#0f172a',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  characterScreenCloseButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
});
