# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BirdGo' do
  config = use_native_modules!
  app_root = File.expand_path('..', __dir__)

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    hermes_cli_path = File.join(
      app_root,
      'node_modules',
      'hermes-compiler',
      'hermesc',
      'osx-bin',
      'hermesc'
    )

    Dir.glob(File.join(__dir__, 'Pods/Target Support Files/**/*.xcconfig')).each do |path|
      next unless File.file?(path)

      contents = File.read(path)
      next unless contents.include?('HERMES_CLI_PATH = ')

      updated_contents = contents.gsub(
        /^HERMES_CLI_PATH = .*$\n?/,
        "HERMES_CLI_PATH = #{hermes_cli_path}\n"
      )
      File.write(path, updated_contents) if updated_contents != contents
    end
  end
end
